# Generated by Django 5.1.6 on 2025-09-16 10:34

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_country_article_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to=articles.models.article_image_directory_path, verbose_name='Изображение'),
        ),
    ]
