# Generated by Django 5.1.6 on 2025-09-17 07:30

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(max_length=250, upload_to=articles.models.article_image_directory_path, verbose_name='Изображение'),
        ),
    ]
